### ISSUE TITLE
We need to finish basic functionalities and to deal with non-functionalities very early before deployment of this system

### ISSUE THREAD

**Issue by deogemini** [deogemini/MPIS#14]

**Comment by kitori-kitori** [comment]
Hakika bro Sent from my Galaxy
-------- Original message --------From: Deo Gemini <notifications@github.com> Date: 02/02/2021  17:31  (GMT+03:00) To: deogemini/MPIS <MPIS@noreply.github.com> Cc: Subscribed <subscribed@noreply.github.com> Subject: [deogemini/MPIS] We need to finish basic functionalities and to deal with non-functionalities very early before deployment of this system (#14)

**Comment by deogemini** [comment]
Let’s work hard

**Comment by kitori-kitori** [comment]
Congratulation guys lets keep working

**Comment by deogemini** [comment]
i think basic functionalities are over let's keep energy on non-functional requirements
